### ISSUE TITLE
Python3 breaks configure on ARCHER

### ISSUE THREAD

**Issue by gnikit** [FluidityProject/buildscripts#2]
Hi @tmbgreaves  I think the latest upgrade to Python3 must have broken the ARCHER configure scripts, since ARCHER does not have python3 by default.

I tried a few different things in the PrgEnv-fluidity file, but none worked.
The weird python-compute/3.6.0_ version causes compilation errors while
loading anaconda/4.3.1-python3 causes PETSc major version to not be detected.
I think that it's just a matter of getting a 3.6 python loaded, I simply don't know the name of the correct package.

Do you think you could have a look at it when you get the change?

Kind regards,
Giannis

**Comment by tmbgreaves** [comment]
Hi @GNikit , and thanks for the heads-up on this one!

My instinct is that the steps for this are:

- Initially, alter the git clone step to pick up a shallow clone of 4.1.16 rather than HEAD, ie:

`git clone -b '4.1.16' --single-branch --depth 1 https://github.com/fluidityproject/fluidity.git`

- I'll drop a line to the support desk and see if they have an existing recommended solution for Python3

- If nothing comes out of the support request, I'll add in a step to download and set up a local anaconda

**Comment by tmbgreaves** [comment]
Hopefully fixed in commit #bedf190
